"""Extracts the animations Focus Cat uses from assets/cat_template.aseprite into
focuscat/sprite_data.py.

The sheet is a grid of 64x64 cells; every row is one animation. Each pixel is stored as a
colour *role* (outline, fur, shadow, ...) so the app can recolour the cat to any look.

    python tools/build_sprites.py
"""
import base64
import json
import os
import sys
import zlib

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import aseprite  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CELL = 64

# Colours of the gray template cat -> role letters.
ROLES = {
    (0x12, 0x0E, 0x14): "O",  # outline
    (0xBD, 0xB5, 0xC8): "F",  # fur
    (0x93, 0x8B, 0x9E): "S",  # fur shadow
    (0xE1, 0xDE, 0xE7): "L",  # light fur (chest, highlights): the second colour on two-tone cats
    (0x9A, 0x87, 0x7E): "P",  # inside of the ears
    (0xD3, 0xDF, 0xE1): "E",  # eyes
    (0xCA, 0x71, 0x9F): "M",  # mouth / tongue
    (0x19, 0x0F, 0x29): "N",  # inside of the mouth
}

# name: (sheet row, has feet on the ground so "socks" make sense)
ANIMS = {
    "sit": (19, True), "blink": (14, True), "sit_l": (21, True), "sit_r": (22, True),
    "stand": (16, True), "stand_l": (25, True), "stand_r": (26, True),
    "walk_l": (4, True), "walk_r": (5, True),
    "groom": (12, True), "scratch": (17, True),
    "sleep_l": (48, False), "sleep_r": (49, False), "loaf_l": (46, False), "loaf_r": (47, False),
    "pounce_l": (63, True), "pounce_r": (64, True),
    "hiss_l": (60, True), "hiss_r": (61, True),
    "happy": (65, True), "meow": (43, True),
}


def cell(rows, r, c):
    return [row[c * CELL:(c + 1) * CELL] for row in rows[r * CELL:(r + 1) * CELL]]


def to_roles(px):
    out = []
    for row in px:
        line = ""
        for p in row:
            if p[3] < 128:
                line += "."
            else:
                role = ROLES.get(p[:3])
                if role is None:
                    raise SystemExit(f"unknown colour {p}")
                line += role
        out.append(line)
    return out


def main():
    doc = aseprite.read(os.path.join(ROOT, "assets", "cat_template.aseprite"))
    rows = aseprite.frame_rgba(doc, 0, ["Layer 1"])
    anims = {}
    for name, (r, feet) in ANIMS.items():
        frames = []
        for c in range(doc["width"] // CELL):
            grid = to_roles(cell(rows, r, c))
            if any(ch != "." for line in grid for ch in line):
                frames.append(grid)
        # One bounding box for the whole animation so frames don't jitter.
        ys = [y for f in frames for y, line in enumerate(f) if line.strip(".")]
        xs = [x for f in frames for line in f for x, ch in enumerate(line) if ch != "."]
        top, bottom, left, right = min(ys), max(ys), min(xs), max(xs)
        cropped = []
        for f in frames:
            g = [line[left:right + 1] for line in f[top:bottom + 1]]
            if feet:
                # Lowercase fur in the bottom three rows = paws, for the "socks" pattern.
                low = max(i for i, line in enumerate(g) if line.strip("."))
                g = [line.translate(str.maketrans("FSL", "fsl")) if i > low - 3 else line
                     for i, line in enumerate(g)]
            cropped.append(g)
        # Head position: middle of the top few rows of the first frame.
        first = cropped[0]
        first_row = next(i for i, line in enumerate(first) if line.strip("."))
        head_rows = [line for line in first[first_row:first_row + 6] if line.strip(".")]
        hx = [x for line in head_rows for x, ch in enumerate(line) if ch != "."]
        anims[name] = {
            "x0": left - CELL // 2,          # left edge relative to the cell centre
            "y0": top - (bottom + 1),        # top edge relative to the ground
            "head_x": left - CELL // 2 + (min(hx) + max(hx)) / 2,
            "frames": ["\n".join(g) for g in cropped],
        }
    blob = base64.b64encode(zlib.compress(json.dumps(anims).encode(), 9)).decode()
    lines = [blob[i:i + 96] for i in range(0, len(blob), 96)]
    with open(os.path.join(ROOT, "focuscat", "sprite_data.py"), "w") as f:
        f.write('"""Generated by tools/build_sprites.py from assets/cat_template.aseprite. Do not edit."""\n\n')
        f.write("DATA = (\n" + "".join(f'    "{line}"\n' for line in lines) + ")\n")
    print(f"{len(anims)} animations, {sum(len(a['frames']) for a in anims.values())} frames, "
          f"{len(blob) // 1024} KB")


if __name__ == "__main__":
    main()
